// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg2JMfXoQoqSQ2gTCpXDKne2H7anEmUwk',
    appId: '1:923713348152:web:967e26f6ff18e775f27ccd',
    messagingSenderId: '923713348152',
    projectId: 'my-ecommerce-app-123-bb538',
    authDomain: 'my-ecommerce-app-123-bb538.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-bb538.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB14JYYm3bDwIuHEj4d7daukR7w-MXzIFk',
    appId: '1:923713348152:android:ea95865ea2208569f27ccd',
    messagingSenderId: '923713348152',
    projectId: 'my-ecommerce-app-123-bb538',
    storageBucket: 'my-ecommerce-app-123-bb538.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxWazfREWeXUyH0nwdRQtc5iOGtCg8EVE',
    appId: '1:923713348152:ios:048f57041bf4d82df27ccd',
    messagingSenderId: '923713348152',
    projectId: 'my-ecommerce-app-123-bb538',
    storageBucket: 'my-ecommerce-app-123-bb538.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
