// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0TUIpDhh3E4ovth1ndkltLJwqKIsrCuE',
    appId: '1:1082678336293:web:333c6946b4a8d859a618cc',
    messagingSenderId: '1082678336293',
    projectId: 'my-ecommerce-app-123-d3f92',
    authDomain: 'my-ecommerce-app-123-d3f92.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-d3f92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXxQKL6V8xeyV5D_eP3lfl2cXgJjidd4Y',
    appId: '1:1082678336293:android:f45e55b5d3d2566aa618cc',
    messagingSenderId: '1082678336293',
    projectId: 'my-ecommerce-app-123-d3f92',
    storageBucket: 'my-ecommerce-app-123-d3f92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDawQPXtLGQQCwHRi7HqTbVRJYI4NLXV4U',
    appId: '1:1082678336293:ios:02b09352c9e52b44a618cc',
    messagingSenderId: '1082678336293',
    projectId: 'my-ecommerce-app-123-d3f92',
    storageBucket: 'my-ecommerce-app-123-d3f92.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
